2022-04-21 04:57:01,161 INFO    MainThread:2307372 [internal.py:wandb_internal():92] W&B internal server running at pid: 2307372, started at: 2022-04-21 04:57:01.161026
2022-04-21 04:57:01,164 INFO    WriterThread:2307372 [datastore.py:open_for_write():77] open: output/query_baseline/wandb/run-20220421_045700-2612om78/run-2612om78.wandb
2022-04-21 04:57:01,166 DEBUG   SenderThread:2307372 [sender.py:send():235] send: header
2022-04-21 04:57:01,166 DEBUG   SenderThread:2307372 [sender.py:send():235] send: run
2022-04-21 04:57:11,826 DEBUG   HandlerThread:2307372 [handler.py:handle_request():141] handle_request: check_version
2022-04-21 04:57:11,827 INFO    SenderThread:2307372 [dir_watcher.py:__init__():169] watching files in: output/query_baseline/wandb/run-20220421_045700-2612om78/files
2022-04-21 04:57:11,827 INFO    SenderThread:2307372 [sender.py:_start_run_threads():812] run started: 2612om78 with start time 1650517020
2022-04-21 04:57:11,827 DEBUG   SenderThread:2307372 [sender.py:send():235] send: summary
2022-04-21 04:57:11,827 INFO    SenderThread:2307372 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-04-21 04:57:11,827 DEBUG   SenderThread:2307372 [sender.py:send_request():249] send_request: check_version
2022-04-21 04:57:12,828 INFO    Thread-7  :2307372 [dir_watcher.py:_on_file_created():217] file/dir created: output/query_baseline/wandb/run-20220421_045700-2612om78/files/wandb-summary.json
2022-04-21 04:57:16,840 DEBUG   HandlerThread:2307372 [handler.py:handle_request():141] handle_request: run_start
2022-04-21 04:57:16,857 DEBUG   HandlerThread:2307372 [meta.py:__init__():37] meta init
2022-04-21 04:57:16,857 DEBUG   HandlerThread:2307372 [meta.py:__init__():51] meta init done
2022-04-21 04:57:16,857 DEBUG   HandlerThread:2307372 [meta.py:probe():211] probe
2022-04-21 04:57:16,867 DEBUG   HandlerThread:2307372 [meta.py:_setup_git():201] setup git
2022-04-21 04:57:16,884 DEBUG   HandlerThread:2307372 [meta.py:_setup_git():208] setup git done
2022-04-21 04:57:16,884 DEBUG   HandlerThread:2307372 [meta.py:_save_pip():55] save pip
2022-04-21 04:57:16,885 DEBUG   HandlerThread:2307372 [meta.py:_save_pip():69] save pip done
2022-04-21 04:57:16,885 DEBUG   HandlerThread:2307372 [meta.py:_save_conda():76] save conda
2022-04-21 04:57:17,830 INFO    Thread-7  :2307372 [dir_watcher.py:_on_file_created():217] file/dir created: output/query_baseline/wandb/run-20220421_045700-2612om78/files/requirements.txt
2022-04-21 04:57:17,830 INFO    Thread-7  :2307372 [dir_watcher.py:_on_file_created():217] file/dir created: output/query_baseline/wandb/run-20220421_045700-2612om78/files/conda-environment.yaml
2022-04-21 04:57:21,537 DEBUG   HandlerThread:2307372 [meta.py:_save_conda():86] save conda done
2022-04-21 04:57:21,538 DEBUG   HandlerThread:2307372 [meta.py:probe():249] probe done
2022-04-21 04:57:21,545 DEBUG   SenderThread:2307372 [sender.py:send():235] send: files
2022-04-21 04:57:21,545 INFO    SenderThread:2307372 [sender.py:_save_file():947] saving file wandb-metadata.json with policy now
2022-04-21 04:57:21,554 DEBUG   HandlerThread:2307372 [handler.py:handle_request():141] handle_request: stop_status
2022-04-21 04:57:21,555 DEBUG   SenderThread:2307372 [sender.py:send_request():249] send_request: stop_status
2022-04-21 04:57:21,832 INFO    Thread-7  :2307372 [dir_watcher.py:_on_file_modified():230] file/dir modified: output/query_baseline/wandb/run-20220421_045700-2612om78/files/conda-environment.yaml
2022-04-21 04:57:21,832 INFO    Thread-7  :2307372 [dir_watcher.py:_on_file_created():217] file/dir created: output/query_baseline/wandb/run-20220421_045700-2612om78/files/output.log
2022-04-21 04:57:21,833 INFO    Thread-7  :2307372 [dir_watcher.py:_on_file_created():217] file/dir created: output/query_baseline/wandb/run-20220421_045700-2612om78/files/wandb-metadata.json
2022-04-21 04:57:22,083 DEBUG   SenderThread:2307372 [sender.py:send():235] send: telemetry
2022-04-21 04:57:37,085 DEBUG   HandlerThread:2307372 [handler.py:handle_request():141] handle_request: stop_status
2022-04-21 04:57:37,254 WARNING FileStreamThread:2307372 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f0d60bd2490>>, args: ('https://api.wandb.ai/files/ruc-bupt/Paddle SINC/2612om78/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2022-04-21 04:57:40,133 DEBUG   SenderThread:2307372 [sender.py:send_request():249] send_request: stop_status
2022-04-21 04:57:40,841 INFO    Thread-7  :2307372 [dir_watcher.py:_on_file_modified():230] file/dir modified: output/query_baseline/wandb/run-20220421_045700-2612om78/files/config.yaml
2022-04-21 04:57:41,633 ERROR   Thread-11 :2307372 [internal_api.py:upload_file():1631] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/wandb-metadata.json?Expires=1650603444&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fPJJ%2BAWNRkQjNApHX%2BzwhydVKNQZbTBZlr9AyzhDCU1e4ZePwMjA%2F4RXPPG54UCa8sgsjAG6h9sdu117QeAdPpMkP%2BaePgr7KfvvlsLeUkG0AUtKOXXI5Cvc0nuv4l3wg1zrJlBG%2BfwDzAFyNGWycYzdO%2Bh4lvG%2BK3iUdqtx6eahZTUaIvnwO61mT%2BG7NzwaVwCUAoMOFtd6JPSgxEyjIQLOWW4c8KciEYof6BTONa0ypcisLqt7YQStmKWsjjPb2OhWIoCzI3XfVX0Vyj3fh5C7C1MjvaneUnvcBRwiXyhRNE1XEG%2FT7OF8IXxrBMOTL19IUuOfFFhtcAkhm5AzQw%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-04-21 04:57:41,633 ERROR   Thread-11 :2307372 [internal_api.py:upload_file():1633] upload_file request headers: {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1269'}
2022-04-21 04:57:41,634 ERROR   Thread-11 :2307372 [internal_api.py:upload_file():1635] upload_file response body: 
2022-04-21 04:57:46,722 DEBUG   SenderThread:2307372 [sender.py:send():235] send: stats
2022-04-21 04:57:47,198 INFO    Thread-11 :2307372 [upload_job.py:push():137] Uploaded file /tmp/tmpusydd9e9wandb/hhuvhw2c-wandb-metadata.json
2022-04-21 04:57:51,819 DEBUG   SenderThread:2307372 [sender.py:send():235] send: telemetry
2022-04-21 04:57:58,223 WARNING MainThread:2307372 [internal.py:is_dead():387] Internal process exiting, parent pid 2307306 disappeared
2022-04-21 04:57:58,224 ERROR   MainThread:2307372 [internal.py:wandb_internal():151] Internal process shutdown.
2022-04-21 04:57:58,821 INFO    WriterThread:2307372 [datastore.py:close():281] close: output/query_baseline/wandb/run-20220421_045700-2612om78/run-2612om78.wandb
2022-04-21 04:57:58,821 INFO    SenderThread:2307372 [sender.py:finish():1107] shutting down sender
2022-04-21 04:57:58,822 INFO    SenderThread:2307372 [dir_watcher.py:finish():283] shutting down directory watcher
2022-04-21 04:57:58,827 INFO    HandlerThread:2307372 [handler.py:finish():790] shutting down handler
2022-04-21 04:57:58,845 INFO    SenderThread:2307372 [dir_watcher.py:finish():313] scan: output/query_baseline/wandb/run-20220421_045700-2612om78/files
2022-04-21 04:57:58,845 INFO    SenderThread:2307372 [dir_watcher.py:finish():327] scan save: output/query_baseline/wandb/run-20220421_045700-2612om78/files/requirements.txt requirements.txt
2022-04-21 04:57:58,846 INFO    SenderThread:2307372 [dir_watcher.py:finish():327] scan save: output/query_baseline/wandb/run-20220421_045700-2612om78/files/output.log output.log
2022-04-21 04:57:58,846 INFO    SenderThread:2307372 [dir_watcher.py:finish():327] scan save: output/query_baseline/wandb/run-20220421_045700-2612om78/files/wandb-summary.json wandb-summary.json
2022-04-21 04:57:58,847 INFO    SenderThread:2307372 [dir_watcher.py:finish():327] scan save: output/query_baseline/wandb/run-20220421_045700-2612om78/files/conda-environment.yaml conda-environment.yaml
2022-04-21 04:57:58,853 INFO    SenderThread:2307372 [dir_watcher.py:finish():327] scan save: output/query_baseline/wandb/run-20220421_045700-2612om78/files/wandb-metadata.json wandb-metadata.json
2022-04-21 04:57:58,853 INFO    SenderThread:2307372 [dir_watcher.py:finish():327] scan save: output/query_baseline/wandb/run-20220421_045700-2612om78/files/config.yaml config.yaml
2022-04-21 04:57:58,865 INFO    SenderThread:2307372 [file_pusher.py:finish():145] shutting down file pusher
2022-04-21 04:57:58,870 INFO    SenderThread:2307372 [file_pusher.py:join():150] waiting for file pusher
2022-04-21 04:57:59,824 INFO    Thread-15 :2307372 [upload_job.py:push():137] Uploaded file output/query_baseline/wandb/run-20220421_045700-2612om78/files/config.yaml
2022-04-21 04:57:59,963 INFO    Thread-14 :2307372 [upload_job.py:push():137] Uploaded file output/query_baseline/wandb/run-20220421_045700-2612om78/files/conda-environment.yaml
2022-04-21 04:58:01,235 INFO    Thread-13 :2307372 [upload_job.py:push():137] Uploaded file output/query_baseline/wandb/run-20220421_045700-2612om78/files/wandb-summary.json
2022-04-21 04:58:47,022 WARNING FileStreamThread:2307372 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 408 Client Error: Request Timeout for url: https://api.wandb.ai/files/ruc-bupt/Paddle%20SINC/2612om78/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f0d60bd2490>>, args: ('https://api.wandb.ai/files/ruc-bupt/Paddle SINC/2612om78/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 0, 'content': ['{"system.gpu.0.gpu": 68.33, "system.gpu.0.memory": 30.4, "system.gpu.0.memoryAllocated": 69.54, "system.gpu.0.temp": 77.27, "system.gpu.0.powerWatts": 157.06, "system.gpu.0.powerPercent": 62.82, "system.gpu.1.gpu": 73.93, "system.gpu.1.memory": 45.47, "system.gpu.1.memoryAllocated": 66.84, "system.gpu.1.temp": 81.53, "system.gpu.process.1.gpu": 76.5, "system.gpu.process.1.memory": 47.0, "system.gpu.process.1.memoryAllocated": 68.03, "system.gpu.process.1.temp": 81.75, "system.gpu.1.powerWatts": 171.6, "system.gpu.1.powerPercent": 68.64, "system.gpu.process.1.powerWatts": 157.71, "system.gpu.process.1.powerPercent": 63.08, "system.gpu.2.gpu": 67.6, "system.gpu.2.memory": 34.33, "system.gpu.2.memoryAllocated": 67.65, "system.gpu.2.temp": 82.73, "system.gpu.2.powerWatts": 155.56, "system.gpu.2.powerPercent": 62.22, "system.gpu.3.gpu": 65.4, "system.gpu.3.memory": 38.0, "system.gpu.3.memoryAllocated": 74.37, "system.gpu.3.temp": 81.8, "system.gpu.3.powerWatts": 164.29, "system.gpu.3.powerPercent": 65.71, "system.cpu": 16.51, "system.memory": 23.3, "system.disk": 14.6, "system.proc.memory.availableMB": 98797.7, "system.proc.memory.rssMB": 118.94, "system.proc.memory.percent": 0.09, "system.proc.cpu.threads": 12.87, "system.network.sent": 229420, "system.network.recv": 219899, "_wandb": true, "_timestamp": 1650517066, "_runtime": 46}']}}, 'dropped': 0}}
2022-04-21 05:03:59,643 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1631] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/requirements.txt?Expires=1650603479&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=eync21PjHBIiwAhEb6YoRz3FOhrz%2FHwKZSgSjlSbMoeN5CElIcdwWgvIJSh2apFtqAdGOoH7H56SXcHQwIS5NSIBPB6t9xh%2BivV%2FA9jgMS7ITbQdR2e0g%2F1eXVAXy%2FPBwNr3RX0pRhU6Dd4lrPJ1U9lKmiV5nJl6xciDe6nNGmqzq4q8Jzza5Dxqod2IQSmh%2FQscV60TZsgsVnx7MckD5na0kXazPUO7wvHyM7VbUcVtz3ZmG%2BRPj%2Fe3oau5%2Bc%2BGEzHl3ZVXfGX3YEuE%2B9dqGnigdhZWoTsRF1hTNQ7%2BZm6E5nuW%2Fr0DNzp9johAYL42pz5j%2FTPQHapu20QW3lTYfw%3D%3D: 408 Client Error: Request Timeout for url: https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/requirements.txt?Expires=1650603479&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=eync21PjHBIiwAhEb6YoRz3FOhrz%2FHwKZSgSjlSbMoeN5CElIcdwWgvIJSh2apFtqAdGOoH7H56SXcHQwIS5NSIBPB6t9xh%2BivV%2FA9jgMS7ITbQdR2e0g%2F1eXVAXy%2FPBwNr3RX0pRhU6Dd4lrPJ1U9lKmiV5nJl6xciDe6nNGmqzq4q8Jzza5Dxqod2IQSmh%2FQscV60TZsgsVnx7MckD5na0kXazPUO7wvHyM7VbUcVtz3ZmG%2BRPj%2Fe3oau5%2Bc%2BGEzHl3ZVXfGX3YEuE%2B9dqGnigdhZWoTsRF1hTNQ7%2BZm6E5nuW%2Fr0DNzp9johAYL42pz5j%2FTPQHapu20QW3lTYfw%3D%3D
2022-04-21 05:03:59,644 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1633] upload_file request headers: {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5474'}
2022-04-21 05:03:59,644 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1635] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 408 (Request Timeout)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>408.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>Your client has taken too long to issue its request.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2022-04-21 05:10:01,089 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1631] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/requirements.txt?Expires=1650603479&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=eync21PjHBIiwAhEb6YoRz3FOhrz%2FHwKZSgSjlSbMoeN5CElIcdwWgvIJSh2apFtqAdGOoH7H56SXcHQwIS5NSIBPB6t9xh%2BivV%2FA9jgMS7ITbQdR2e0g%2F1eXVAXy%2FPBwNr3RX0pRhU6Dd4lrPJ1U9lKmiV5nJl6xciDe6nNGmqzq4q8Jzza5Dxqod2IQSmh%2FQscV60TZsgsVnx7MckD5na0kXazPUO7wvHyM7VbUcVtz3ZmG%2BRPj%2Fe3oau5%2Bc%2BGEzHl3ZVXfGX3YEuE%2B9dqGnigdhZWoTsRF1hTNQ7%2BZm6E5nuW%2Fr0DNzp9johAYL42pz5j%2FTPQHapu20QW3lTYfw%3D%3D: 408 Client Error: Request Timeout for url: https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/requirements.txt?Expires=1650603479&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=eync21PjHBIiwAhEb6YoRz3FOhrz%2FHwKZSgSjlSbMoeN5CElIcdwWgvIJSh2apFtqAdGOoH7H56SXcHQwIS5NSIBPB6t9xh%2BivV%2FA9jgMS7ITbQdR2e0g%2F1eXVAXy%2FPBwNr3RX0pRhU6Dd4lrPJ1U9lKmiV5nJl6xciDe6nNGmqzq4q8Jzza5Dxqod2IQSmh%2FQscV60TZsgsVnx7MckD5na0kXazPUO7wvHyM7VbUcVtz3ZmG%2BRPj%2Fe3oau5%2Bc%2BGEzHl3ZVXfGX3YEuE%2B9dqGnigdhZWoTsRF1hTNQ7%2BZm6E5nuW%2Fr0DNzp9johAYL42pz5j%2FTPQHapu20QW3lTYfw%3D%3D
2022-04-21 05:10:01,089 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1633] upload_file request headers: {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5474'}
2022-04-21 05:10:01,089 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1635] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 408 (Request Timeout)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>408.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>Your client has taken too long to issue its request.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2022-04-21 05:16:35,206 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1631] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/requirements.txt?Expires=1650603479&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=eync21PjHBIiwAhEb6YoRz3FOhrz%2FHwKZSgSjlSbMoeN5CElIcdwWgvIJSh2apFtqAdGOoH7H56SXcHQwIS5NSIBPB6t9xh%2BivV%2FA9jgMS7ITbQdR2e0g%2F1eXVAXy%2FPBwNr3RX0pRhU6Dd4lrPJ1U9lKmiV5nJl6xciDe6nNGmqzq4q8Jzza5Dxqod2IQSmh%2FQscV60TZsgsVnx7MckD5na0kXazPUO7wvHyM7VbUcVtz3ZmG%2BRPj%2Fe3oau5%2Bc%2BGEzHl3ZVXfGX3YEuE%2B9dqGnigdhZWoTsRF1hTNQ7%2BZm6E5nuW%2Fr0DNzp9johAYL42pz5j%2FTPQHapu20QW3lTYfw%3D%3D: 408 Client Error: Request Timeout for url: https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/requirements.txt?Expires=1650603479&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=eync21PjHBIiwAhEb6YoRz3FOhrz%2FHwKZSgSjlSbMoeN5CElIcdwWgvIJSh2apFtqAdGOoH7H56SXcHQwIS5NSIBPB6t9xh%2BivV%2FA9jgMS7ITbQdR2e0g%2F1eXVAXy%2FPBwNr3RX0pRhU6Dd4lrPJ1U9lKmiV5nJl6xciDe6nNGmqzq4q8Jzza5Dxqod2IQSmh%2FQscV60TZsgsVnx7MckD5na0kXazPUO7wvHyM7VbUcVtz3ZmG%2BRPj%2Fe3oau5%2Bc%2BGEzHl3ZVXfGX3YEuE%2B9dqGnigdhZWoTsRF1hTNQ7%2BZm6E5nuW%2Fr0DNzp9johAYL42pz5j%2FTPQHapu20QW3lTYfw%3D%3D
2022-04-21 05:16:35,207 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1633] upload_file request headers: {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5474'}
2022-04-21 05:16:35,207 ERROR   Thread-12 :2307372 [internal_api.py:upload_file():1635] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 408 (Request Timeout)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>408.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>Your client has taken too long to issue its request.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2022-04-21 05:16:35,207 ERROR   Thread-12 :2307372 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home2/gaobofei/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1629, in upload_file
  File "/home2/gaobofei/anaconda3/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 408 Client Error: Request Timeout for url: https://storage.googleapis.com/wandb-production.appspot.com/ruc-bupt/Paddle%20SINC/2612om78/requirements.txt?Expires=1650603479&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=eync21PjHBIiwAhEb6YoRz3FOhrz%2FHwKZSgSjlSbMoeN5CElIcdwWgvIJSh2apFtqAdGOoH7H56SXcHQwIS5NSIBPB6t9xh%2BivV%2FA9jgMS7ITbQdR2e0g%2F1eXVAXy%2FPBwNr3RX0pRhU6Dd4lrPJ1U9lKmiV5nJl6xciDe6nNGmqzq4q8Jzza5Dxqod2IQSmh%2FQscV60TZsgsVnx7MckD5na0kXazPUO7wvHyM7VbUcVtz3ZmG%2BRPj%2Fe3oau5%2Bc%2BGEzHl3ZVXfGX3YEuE%2B9dqGnigdhZWoTsRF1hTNQ7%2BZm6E5nuW%2Fr0DNzp9johAYL42pz5j%2FTPQHapu20QW3lTYfw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/gaobofei/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
  File "/home2/gaobofei/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1644, in upload_file
  File "/home2/gaobofei/anaconda3/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home2/gaobofei/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1629, in upload_file
  File "/home2/gaobofei/anaconda3/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2022-04-21 05:16:40,409 INFO    Thread-12 :2307372 [upload_job.py:push():137] Uploaded file output/query_baseline/wandb/run-20220421_045700-2612om78/files/requirements.txt
